### PR TITLE
fix: redbox should be scrollable

### PR DESCRIPTION
**Pull request by wagerfield**
View errors that are rendered off screen

### CODE REVIEW

**Comment by davidpfahler** [comment]
@wagerfield Thank you for submitting a pull request and contributing to redbox! To be able to merge your code, could you please describe the problem and ideally provide a test case and/or screenshot, so I can see what problem you have solved. We also need to make sure this is not in conflict with any existing code. Thanks.

**Comment by wagerfield** [comment]
Sure, no problem. 

Without `overflow: scroll`, you are unable to scroll down through the error stack trace on vertically narrow screens:

screen shot 2016-09-18 at 17 09 35

> ^^^ cannot scroll down

With `overflow: scroll` you can:

screen shot 2016-09-18 at 17 10 35

> ^^^ can scroll down

**Comment by davidpfahler** [comment]
@wagerfield If you are not sure how to do that, I can do it for you, just let me know how you want to continue.

**Comment by mxlje** [comment]
Thank you 🎉

**Pull request merged**
