### PR TITLE
Changes the overflow  to auto for show scroll bars only if is needed

### PR DESCRIPTION
**Pull request by dbeff**
With `overflow: scroll;`

image

With `overflow: auto;`

image

### CODE REVIEW

**Comment by dbeff** [comment]
It is a small change but I hope it is to help this awesome tool.  😀

**Comment by davidpfahler** [comment]
@dbeff Thanks for your contribution and the flowers. `overflow: auto` gives control to the browser, so I don't know exactly what the result will be in each browser, but I would't veto this change. 

@mxlje Do you think this is good to merge?

**Comment by mxlje** [comment]
@dbeff 

I apologize for the delay here. I merged your changes in #87 as I had to update the commit message to match the semantic release guidelines. Version `1.3.4` is now live on [npm](https://www.npmjs.com/package/redbox-react).

**Comment by dbeff** [comment]
Thank you guys! And congratulations for the amazing work with this package!

**Pull request closed without merging**
