### PR TITLE
Adding React 16 & 16 beta support

### PR DESCRIPTION
**Pull request by mikecousins**

### CODE REVIEW

**Comment by mxlje** [comment]
Hey @mikecousins, thank you for your contribution to redbox!

Please rebase your commit and prefix the commit message with `feat:`, that way we can automatically release your changes as a new version on npm. Thanks :tada:

**Comment by borela** [comment]
I believe peer dependencies needs to be updated too.

**Comment by mikecousins** [comment]
You're right I forgot the peerDependencies as well. Sorry guys. Fix coming shortly.

**Comment by mikecousins** [comment]
@mxlje I don't know how many I need to change with the feat: prefix, but I amended one of them for now. Let me know if that's okay.

**Comment by mikecousins** [comment]
I also figured that I should just update the peer dependencies for now. dev dependencies don't really matter.

**Comment by mxlje** [comment]
@mikecousins in this case it would be best to squash all your commits into a single one with a `feat:` prefix in the message. Thank you!

**Comment by mikecousins** [comment]
Can you do that when you merge it in? I'm having difficulty getting it to work.

**Comment by mxlje** [comment]
@mikecousins No worries! I rebased and merged your changes in #105.
Thanks for your contribution 🎉

**Comment by mikecousins** [comment]
Thanks!

**Pull request closed without merging**
