### PR TITLE
TypeScript declaration file

### PR DESCRIPTION
**Pull request by dylanscott**
Hey, I was wondering if you'd consider a PR to add a declaration file to make using this library from TypeScript easier

### CODE REVIEW

**Comment by davidpfahler** [comment]
@dylanscott Sure, I don't see any downsides to this, but I must admit that I have no knowledge on TypeScript whatsoever. @mxlje ?

**Comment by mxlje** [comment]
I have no real knowledge of TypeScript either, but am not opposed to improving usability for it. If you submit a PR with the necessary changes as well as a good explanation of what it does and why it is needed, I see no problem getting it merged. Thank you.

**Comment by mxlje** [comment]
Also, Sorry, i didn't see that this is already PR and not just an issue asking for a potential PR. Are your changes all that is needed? Can we add tests or something along those lines? If not, I'm fine merging as is.

**Comment by dylanscott** [comment]
@mxlje This should be all the changes that are necessary. I've just added a small test for the declaration file as well. Unfortunately I'm not sure the best way to do negative testing (code that wouldn't compile) since I'm just running the compiler as the "test runner", but this at least checks all the documented props.

**Comment by davidpfahler** [comment]
@dylanscott Thank you for your contribution. I am getting a little worried about this, however. I don't think I can maintain the TypeScript type annotations and as you just added them to the test, this means my tests will break the future and I don't know how to change them. I am honestly not sure how to square that circle.

**Comment by dylanscott** [comment]
@davidpfahler that's a fair concern. I was imagining this library wouldn't be changing too much, but I can submit these typings in an alternative way (to an external typings repository where the burden of keeping them up to date would not be on you).

**Comment by davidpfahler** [comment]
@dylanscott Let's try it. I can always remove it again, if I really run into problems.

**Comment by dylanscott** [comment]
@davidpfahler much appreciated! And I'm more than happy to help keep these up-to-date if that becomes necessary

**Comment by davidpfahler** [comment]
@dylanscott Thank you! I am very happy to have you on board as a Contributor.

**Pull request merged**
